# Generated by Django 4.2.11 on 2024-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_destinations',
            name='map_link',
            field=models.URLField(max_length=700),
        ),
    ]
